### PR TITLE
Improved the code quality and more.

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
```diff
+ Improved the code quality
+ Skip download of existing chapters/pages.

- Replaced all the tabs with spaces (4 spaces per tab).
```

Welp, that was all.
Hope you like this PR.

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
There was a small bug (introduced by my code) but I fixed it.

**Comment by ArjixWasTaken** [comment]
Actually from what I see that API ratelimit is gone?
So this is indeed way faster than before.

I do wonder tho, why was the ratelimit removed?

Anyways, if its added back and its the same as it was before, then this code should not break.

**Comment by ArjixWasTaken** [comment]
turns out the ratelimit is still there?

nah, its not, its just ddos-guard

**Comment by ArjixWasTaken** [comment]
Welp, from now on I follow the old approach of sleeping on every api call.

**Comment by orbea** [comment]
@ArjixWasTaken I am not responsible for this repo, but it might be easier to review this by breaking it up into smaller pieces in new PRs.

> Skip download of existing chapters/pages.

This seems potentially useful, maybe you could start there?

**Comment by ArjixWasTaken** [comment]
> @ArjixWasTaken I am not responsible for this repo, but it might be easier to review this by breaking it up into smaller pieces in new PRs.
> 
> > Skip download of existing chapters/pages.
> 
> This seems potentially useful, maybe you could start there?

I can surely do that.
But uhh...
Since I do change the tabs to spaces, it would have conflicts with the PR that skips existing chapters.

**Comment by orbea** [comment]
I would advise making any stylistic changes in their own PR with no unrelated changes, I am not sure if @frozenpandaman would be open to changing spacing or not.

**Comment by ArjixWasTaken** [comment]
> I would advise making any stylistic changes in their own PR with no unrelated changes, I am not sure if @frozenpandaman would be open to changing spacing or not.

I guess that makes sense, but that would mean that I would have to wait for one PR to be merged before making another one.

**Comment by orbea** [comment]
You can always make multiple PRs and rebase them as needed, but yea, that is a consequence of making them easier to review and merge. Its probably better than a giant hard to review PR that sits around indefinitely.

**Comment by ArjixWasTaken** [comment]
Closing this in favor of separate PR's.

**Comment by frozenpandaman** [comment]
> I would advise making any stylistic changes in their own PR with no unrelated changes, I am not sure if @frozenpandaman would be open to changing spacing or not.

Correct, thanks @orbea. I want to leave the spacing as tabs.

> Closing this in favor of separate PR's.

Thanks @ArjixWasTaken, this was getting a little unmanageable to figure out what'd been changed, even. That also made it even more daunting to look at which is partly why it ended up sitting around for longer than ideal.

**Pull request closed without merging**
