### PR TITLE
Update for the latest MangaDex API

### PR DESCRIPTION
**Pull request by doroshenko**

### CODE REVIEW

**Comment by orbea** [comment]
Works for me too, thanks!

**Comment by frozenpandaman** [comment]
They keep changing things around, huh…

Thanks a ton!

**Comment by orbea** [comment]
They still show `MangaDex is still in early access—bugs are to be expected.` so that presumably further breakage may happen in the future.

**Comment by frozenpandaman** [comment]
Haha, I know, just interesting they're arbitrarily (?) changing things like this even still going on months now.

**Pull request merged**
