### PR TITLE
Retry image downloads.

### LINKED ISSUE #20: Retry downloads before failing.
Sometimes when using `mangadex-dl` it will trigger intermittent download errors where retrying one or more times will result in the download working.

I think it would be better if `mangadex-dl` would try the download a few times before deciding the download link did not work. I made this small hack which works sometimes, but someone that knows python could probably do better.
```
diff --git a/mangadex-dl.py b/mangadex-dl.py
index ba98df4..106c70c 100755
--- a/mangadex-dl.py
+++ b/mangadex-dl.py
@@ -133,7 +133,13 @@ def dl(manga_id, lang_code, tld="org"):
 				with open(outfile, 'wb') as f:
 					f.write(r.content)
 			else:
-				print("Encountered Error {} when downloading.".format(e.code))
+				time.sleep(5)
+				r = scraper.get(url)
+				if r.status_code == 200:
+					with open(outfile, 'wb') as f:
+						f.write(r.content)
+				else:
+					print("Encountered Error {} when downloading.".format(e.code))
 
 			print(" Downloaded page {}.".format(pagenum))
 			time.sleep(1)

```

### PR DESCRIPTION
**Pull request by orbea**
This was rebased and slightly modified from PR https://github.com/frozenpandaman/mangadex-dl/pull/12.

Please see: https://github.com/frozenpandaman/mangadex-dl/commit/49d46b106e0075a4a977a11b5b85a66eb0991d1d#diff-bf42877ca45a297d4c75224245657926R138

Fixes https://github.com/frozenpandaman/mangadex-dl/issues/20

### CODE REVIEW

**Comment by orbea** [comment]
@frozenpandaman Would you mind reviewing the PRs when you have a chance?

**Comment by frozenpandaman** [comment]
@orbea Really sorry for the delay/inactivity! I have so much going on right now and unfortunately this just can't be my priority, but I do want to get to it. :( I will try my very hardest to catch up with all the activity here and spend some time on this project next month.

**Comment by orbea** [comment]
No worries and thanks for the reply.

**Comment by orbea** [comment]
@frozenpandaman I rebased the first commit and added a second commit to retry the chapter downloads too. I have been running mangadex-dl like this for a while and haven't seen it fail due to intermittent network failures yet.

The first commit is the much more common case since there are obviously more pages than chapters, but the second one sometimes happens too.

**Pull request closed without merging**
