### PR TITLE
configurable output directory

### PR DESCRIPTION
**Pull request by TimH96**
made output directory configurable via ``-o`` flag, using the previously hardcoded ``download`` as default

EDIT: sorry about the messed commit history, should have cherry picked instead of reverted but hope thats fine

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
> EDIT: sorry about the messed commit history, should have cherry picked instead of reverted but hope thats fine

I bet it will get rejected because of that dumb reason, just like my PR

**Comment by frozenpandaman** [comment]
@TimH96 Looks good to me, thanks! No worries about the commit history, I'll just squash it. :) Updated the readme to make it easier to understand all the different (all optional, for now!) flags too.

EDIT: Whoops, deleted myself as a co-author there, whatever haha.

**Comment by ArjixWasTaken** [comment]
Heh, nice job deleting my comment.

**Comment by frozenpandaman** [comment]
@ArjixWasTaken Your PR wasn't closed because of too many commits, as you snidely suggested in your off-topic reply (which yes, I obviously deleted in attempt to avoid something like this) – it was closed because it was a bit of a mess. For me, at least, it was hard to understand (even looking at the combined view), with significant changes with little explanation, and others that I just didn't want in the script. Another user agreed,  too: "it would be nice if this could be rebased into coherent commits that make one complete change at a time." I welcomed you to make another, scoped-down PR. That offer is still open if you wish.

This is all completely irrelevant to *this* PR, though, and I'm closing the discussion.

**Pull request merged**
