### PR TITLE
Fixes to float conversion and TLD changes

### PR DESCRIPTION
**Pull request by matty0005**
The new version dynamically changes the tld of the url in accordance to the input address - useful when the url changes.
Also fixes to the error: 'ValueError: could not convert string to float'

### CODE REVIEW

**Comment by frozenpandaman** [comment]
Don't know how to cherry pick from a commit/PR, so added in your changes manually… hope that's alright! 🙃(The ValueError bit was already fixed in the `oneshot_dl` branch.)

**Comment by orbea** [comment]
@frozenpandaman This commit breaks links with a `www`.

This doesn't work.

https://www.mangadex.org/title/9676/azumi

While this does.

https://mangadex.org/title/9676/azumi

**Comment by matty0005** [comment]
@orbea, you can fix this by replacing line 157 `url = input("Enter manga URL: ").strip()` with `url = input("Enter manga URL: ").strip().replace("www.", "")`

**Comment by orbea** [comment]
@matty0005 Yes

This fixes it here with both variations of the example links, thanks.
```
diff --git a/mangadex-dl.py b/mangadex-dl.py
index 2951920..6c0bc02 100755
--- a/mangadex-dl.py
+++ b/mangadex-dl.py
@@ -154,7 +154,7 @@ if __name__ == "__main__":
 
        url = ""
        while url == "":
-               url = input("Enter manga URL: ").strip()
+               url = input("Enter manga URL: ").strip().replace("www.", "")
        try:
                manga_id = re.search("[0-9]+", url).group(0)
                split_url = url.split("/")
```

**Comment by frozenpandaman** [comment]
Thanks for the heads up @orbea! I've fixed this in 58ca201. I've taken a slightly more elegant solution to just stripping out any "www." and instead it just ascertains the TLD from the end or the URL (index `-1`) instead of the second element from the beginning (index `1`) – that way it doesn't matter what subdomains, if any, are given:

https://github.com/frozenpandaman/mangadex-dl/blob/58ca201724bb7527b68bf2b478129778da30df46/mangadex-dl.py#L164

**Pull request closed without merging**
